name: blank

on:
  workflow_dispatch:

jobs:
  blank:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: "docker build -t blank:el8 -f Dockerfile-el8 context"

      - run: "docker run blank:el8"
